title: Harisankar Suresh Portfolio
email: harisankarsuresh100@gmail.com
description: >-
  Portfolio of Harisankar Suresh, a data scientist and computational engineer specializing in
  automation, database workflows, and battery modeling for EV systems.
theme: minima
baseurl: ""
url: "https://harisankarsuresh.github.io"

# Navigation
nav:
  - title: "Home"
    url: "/index.html"
  - title: "Experience"
    url: "/index.html#experience"
  - title: "Projects"
    url: "/index.html#projects"
  - title: "Skills"
    url: "/skills.html"
  - title: "Contact"
    url: "/index.html#contact"
